# 4.1 NumPy的ndarray：一种多维数组对象---------------------------------------------------

# 创建ndarray

In [1]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [2]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr2.ndim

2

In [4]:
arr2.shape

(2, 4)

In [5]:
arr2.dtype

dtype('int32')

In [6]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [7]:
np.empty((3,6))

array([[  2.50425716e-312,   0.00000000e+000,   3.62633684e+228,
          1.96086871e+243,   4.31355366e-096,   1.04716878e-142],
       [  4.54813897e-144,   5.83001600e+199,   7.48468178e+251,
          5.04621362e+180,   7.49779533e+247,   3.88625532e+285],
       [  2.02647441e+267,   1.16317829e-028,   8.76739488e+252,
          1.14011198e+243,   5.54175224e+257,   3.93372943e-317]])

In [8]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

> 表4-1列出了一些数组创建函数。由于NumPy关注的是数值计算，因此，如果没有特别指定，数据类型基本都是float64（浮点数）。

> array | asarray | arange | ones,ones_like | zeros,zeros_like | empty,empty_like | full,full_like | eye,identity

# ndarray的数据类型

> 表4-2列出了NumPy所支持的全部数据类型。

> int8 unit8 | int16 unit16 | int32 unit32 | int64 unit64 | float16 float32 float64 float128 | complex64 complex128 complex256 | bool | object | string\_ | unicode\_ |

In [9]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [10]:
float_arr = arr.astype(np.float64)
float_arr

array([ 1.,  2.,  3.,  4.,  5.])

In [11]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'],
      dtype='|S4')

In [12]:
numeric_strings.astype(np.float)

array([  1.25,  -9.6 ,  42.  ])

** 笔记：调用astype总会创建一个新的数组（一个数据的备份），即使新的dtype与旧的dtype相同。 **

# NumPy数组的运算

In [13]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

# 基本的索引和切片 Basic Indexing and Slicing

In [14]:
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [15]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,     9])

** 注意：如果你想要得到的是ndarray切片的一份副本而非视图，就需要明确地进行复制操作，例如arr[5:8].copy()。**

In [16]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

因此，可以对各个元素进行递归访问，但这样需要做的事情有点多。
你可以传入一个以逗号隔开的索引列表来选取单个元素。也就是说，下面两种方式是等价的：

In [17]:
arr2d[0][2]

3

In [18]:
arr2d[0,2]

3

** 图4-1说明了二维数组的索引方式。轴0作为行axis=0，轴1作为列axis=1。 **

在多维数组中，如果省略了后面的索引，则返回对象会是一个维度低一点的ndarray（它含有高一级维度上的所有数据）。因此，在2×2×3数组arr3d中：

In [19]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
 arr3d[1, 0]

array([7, 8, 9])

In [22]:
arr3d[1][0]

array([7, 8, 9])

# 切片索引 Indexing with slices

In [23]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [26]:
arr2d[1,:2]

array([4, 5])

In [27]:
arr2d[:2, 2]

array([3, 6])

** 图4-2对此进行了说明。注意，“只有冒号”表示选取整个轴，因此你可以像下面这样只对高维轴进行切片：**

# 布尔型索引 Boolean Indexing

In [28]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
data

array([[-0.55889564, -0.03107266,  0.0205062 ,  0.69506053],
       [-0.29890616, -0.320764  , -0.81942595,  0.83739916],
       [-1.00780102, -0.7049017 ,  1.16418913,  0.11080869],
       [ 0.08593853, -0.91593327, -0.9771533 ,  0.8636464 ],
       [ 1.84193204, -1.56881485, -0.0510693 ,  0.40615927],
       [ 0.42465311, -0.28920423, -0.78641765,  1.1484517 ],
       [-1.1147621 ,  0.19215596, -0.51492643,  1.13101093]])

In [29]:
names =='Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [30]:
data[names=='Bob']

array([[-0.55889564, -0.03107266,  0.0205062 ,  0.69506053],
       [ 0.08593853, -0.91593327, -0.9771533 ,  0.8636464 ]])

In [31]:
data[names == 'Bob', 2:]

array([[ 0.0205062 ,  0.69506053],
       [-0.9771533 ,  0.8636464 ]])

In [32]:
data[~(names == 'Bob')]

array([[-0.29890616, -0.320764  , -0.81942595,  0.83739916],
       [-1.00780102, -0.7049017 ,  1.16418913,  0.11080869],
       [ 1.84193204, -1.56881485, -0.0510693 ,  0.40615927],
       [ 0.42465311, -0.28920423, -0.78641765,  1.1484517 ],
       [-1.1147621 ,  0.19215596, -0.51492643,  1.13101093]])

** 通过布尔型索引选取数组中的数据，将总是创建数据的副本，即使返回一模一样的数组也是如此。**

In [33]:
data[data < 0] = 0
data

array([[ 0.        ,  0.        ,  0.0205062 ,  0.69506053],
       [ 0.        ,  0.        ,  0.        ,  0.83739916],
       [ 0.        ,  0.        ,  1.16418913,  0.11080869],
       [ 0.08593853,  0.        ,  0.        ,  0.8636464 ],
       [ 1.84193204,  0.        ,  0.        ,  0.40615927],
       [ 0.42465311,  0.        ,  0.        ,  1.1484517 ],
       [ 0.        ,  0.19215596,  0.        ,  1.13101093]])

# 花式索引 Fancy Indexing

In [34]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [35]:
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [36]:
arr[[-3,-5,-7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

** 一次传入多个索引数组会有一点特别。它返回的是一个一维数组，其中的元素对应各个索引元组：**

In [37]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [38]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [39]:
 arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

** 记住，花式索引跟切片不一样，它总是将数据复制到新数组中。 **

# 数组转置和轴对换 Transposing Arrays and Swapping Axes

转置是重塑的一种特殊形式，它返回的是**源数据的视图**（不会进行任何复制操作）。数组不仅有transpose方法，还有一个特殊的T属性：

In [40]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [42]:
arr = np.random.randn(6, 3)
np.dot(arr.T, arr)

array([[  5.29763486,   2.06853955,   2.25820077],
       [  2.06853955,  10.85530421,   2.50930534],
       [  2.25820077,   2.50930534,   1.89721351]])

对于高维数组，transpose需要得到一个由轴编号组成的元组才能对这些轴进行转置（比较费脑子）：

In [43]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [44]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [45]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

简单的转置可以使用.T，它其实就是进行轴对换而已。ndarray还有一个swapaxes方法，它需要接受一对轴编号：

In [46]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [47]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [48]:
arr.transpose(0,2,1)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# 4.2 通用函数：快速的元素级数组函数----------------------------------------------------------

In [49]:
x = np.random.randn(8)
y = np.random.randn(8)
np.maximum(x,y)

array([-0.0598088 ,  1.24016071, -1.07135902, -0.19562495,  0.46761513,
        1.18004968,  1.55627539,  0.55521118])

In [50]:
arr = np.random.randn(7) * 5
arr

array([-5.52377669,  0.10477446,  5.5735661 , -2.19106256,  7.47660396,
        8.57980957,  4.86653989])

In [51]:
remainder, whole_part = np.modf(arr)
remainder

array([-0.52377669,  0.10477446,  0.5735661 , -0.19106256,  0.47660396,
        0.57980957,  0.86653989])

In [52]:
whole_part

array([-5.,  0.,  5., -2.,  7.,  8.,  4.])

In [53]:
np.sqrt(arr)

D:\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([        nan,  0.32368883,  2.36084013,         nan,  2.73433794,
        2.9291312 ,  2.20602355])

In [54]:
np.sqrt(arr, arr)
arr

D:\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([        nan,  0.32368883,  2.36084013,         nan,  2.73433794,
        2.9291312 ,  2.20602355])

> 表4-3和表4-4分别列出了一些一元和二元ufunc。

> 一元ufunc重点 | ceiling floor | isnan | logical_not | 

> 二元func重点 | add subtract multiply divide floor_divide | 

# 4.3 利用数组进行数据处理--------------------------------------------------------------------------

In [55]:
points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points,points)
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [56]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [57]:
z = np.sqrt(xs**2+ys**2)
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [58]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray)
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

# 将条件逻辑表述为数组运算

In [59]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [60]:
result = [(x if c else y) for x,y,c in zip(xarr, yarr, cond)]
result

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]

In [61]:
result = np.where(cond, xarr, yarr)
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [62]:
arr = np.random.randn(4,4)
np.where(arr>0, 2, arr)

array([[ 2.        ,  2.        ,  2.        , -1.32834833],
       [ 2.        ,  2.        , -0.25531182,  2.        ],
       [ 2.        , -0.45760026, -0.70744149,  2.        ],
       [-0.32651543,  2.        ,  2.        , -0.35188614]])

# 数学和统计方法

In [63]:
arr = np.random.randn(5, 4)
arr

array([[-0.68552244, -1.2697435 ,  1.02615484,  0.63704882],
       [-0.0676145 , -0.27406823, -0.02420291, -0.5092703 ],
       [-0.26292455, -0.21641726, -0.61340309, -1.0345382 ],
       [-1.10026202,  1.12349234,  0.52009135, -0.39558233],
       [-0.90205522, -2.38252344,  0.04123329,  0.32829622]])

In [64]:
arr.mean()

-0.30309055687971137

In [65]:
np.mean(arr)

-0.30309055687971137

In [66]:
arr.mean(axis=1)

array([-0.07301557, -0.21878898, -0.53182077,  0.03693483, -0.72876229])

In [67]:
arr.sum(0)

array([-3.01837872, -3.0192601 ,  0.94987347, -0.97404579])

In [68]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [69]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [71]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

> 表4-5列出了全部的基本数组统计方法。后续章节中有很多例子都会用到这些方法。

> sum | mean | std var | min max | argmin argmax | cumsum cumprod |

# 用于布尔型数组的方法

In [72]:
arr = np.random.randn(100)
(arr > 0).sum()

45

另外还有两个方法any和all，它们对布尔型数组非常有用。any用于测试数组中是否存在一个或多个True，而all则检查数组中所有值是否都是True：
这两个方法也能用于非布尔型数组，所有非0元素将会被当做True。

In [73]:
bools = np.array([False, False, True, False])
bools.any()

True

In [74]:
bools.all()

False

# 排序 Sorting

跟Python内置的列表类型一样，NumPy数组也可以通过sort方法**就地**排序：

In [75]:
arr = np.random.randn(6)
arr

array([-0.86466455,  0.70610006, -0.48009637, -1.77806545, -0.884192  ,
       -0.86739208])

In [76]:
arr.sort()
arr

array([-1.77806545, -0.884192  , -0.86739208, -0.86466455, -0.48009637,
        0.70610006])

In [77]:
arr = np.random.randn(5, 3)
arr

array([[-1.86911282,  0.69431615, -0.62173192],
       [ 0.10751785, -0.80405236, -0.815596  ],
       [ 0.5740208 ,  0.55886985, -0.89692943],
       [ 0.2474845 ,  0.75857355,  1.54661962],
       [-0.5061683 ,  0.95304298,  3.14887293]])

In [78]:
arr.sort(axis=1)
arr

array([[-1.86911282, -0.62173192,  0.69431615],
       [-0.815596  , -0.80405236,  0.10751785],
       [-0.89692943,  0.55886985,  0.5740208 ],
       [ 0.2474845 ,  0.75857355,  1.54661962],
       [-0.5061683 ,  0.95304298,  3.14887293]])

顶级方法np.sort返回的是数组的**已排序副本**，而就地排序则会修改数组本身。
计算数组分位数最简单的办法是对其进行排序，然后选取特定位置的值：

In [79]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05*len(large_arr))]    # 5%的分位数值

-1.5967037670567636

# 唯一化以及其它的集合逻辑

In [80]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [81]:
np.unique(names)

array(['Bob', 'Joe', 'Will'],
      dtype='<U4')

In [82]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [83]:
sorted(set(names))    #纯python处理

['Bob', 'Joe', 'Will']

In [84]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)

> NumPy中的集合函数请参见表4-6。

> unique | intersect1d | union1d | in1d | setdiff1d | setxor1d |

# 4.4 用于数组的文件输入输出------------------------------------------------------------------------

NumPy能够读写磁盘上的文本数据或二进制数据。这一小节只讨论NumPy的内置二进制格式，
因为更多的用户会使用pandas或其它工具加载文本或表格数据（见第6章）。

np.save和np.load是读写磁盘数组数据的两个主要函数。默认情况下，数组是以未压缩的原始二进制格式保存在扩展名为.npy的文件中的：

In [86]:
arr = np.arange(10)
np.savez('some_array',a=arr, b=arr)   # 会自动添加扩展名

In [87]:
arch = np.load('some_array.npz')
arch

In [88]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 4.5 线性代数-------------------------------------------------------------------------------------------

In [89]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [90]:
np.dot(x, np.ones(3))

array([  6.,  15.])

In [91]:
x @ np.ones(3)

array([  6.,  15.])

> 表4-7中列出了一些最常用的线性代数函数。

> diag | dot | trace | det | eig | inv | pinv | qr | svd | solve | lstsq

# 4.6 伪随机数生成----------------------------------------------------------------------------------

In [92]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

1 loop, best of 3: 2.19 s per loop


In [93]:
%timeit np.random.normal(size=N)

10 loops, best of 3: 73.1 ms per loop


In [94]:
np.random.seed(1234)

In [95]:
rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

> 表4-8列出了numpy.random中的部分函数。在下一节中，我将给出一些利用这些函数一次性生成大量样本值的范例。

> seed | permutation | shuffle | rand | randint | randn | binomial | normal | beta | chisquare | gamma | uniform |

# 4.7 示例：随机漫步----------------------------------------------------------------------------------

In [96]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)
plt.plot(walk[:100])

In [97]:
nsteps = 1000
draws = np.random.randint(0,2,size=nsteps)
# draws
steps = np.where(draws>0, 1, -1)
walk = steps.cumsum()

In [98]:
walk.min()

-9

In [99]:
walk.max()

60

# 一次模拟多个随机漫步

In [100]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps))
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)   #按列求累加值
walks.shape

(5000, 1000)

In [101]:
hits30 = (np.abs(walks)>=30).any(1)
hits30.shape

(5000,)

In [102]:
hits30.sum()

3368

In [103]:
crossing_times = (np.abs(walks[hits30])>=30).argmax(1)
crossing_times.shape

(3368,)